version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:8080/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  scheduler:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    command: ["node", "dist/scheduler.js"]
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          node -e "try { const fs = require('fs'); const data = JSON.parse(fs.readFileSync('/tmp/scheduler-heartbeat.json', 'utf8')); if (!data.timestamp) process.exit(1); const age = Date.now() - Date.parse(data.timestamp); if (!Number.isFinite(age) || age > 120000) process.exit(1); process.exit(0); } catch (error) { process.exit(1); }"
      interval: 60s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8080
    environment:
      - VITE_API_URL=http://localhost:8080
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
