services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    ports:
      - "8080:8080"
    restart: unless-stopped

  scheduler:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    command: ["node", "dist/scheduler.js"]
    depends_on:
      - backend
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8080
    environment:
      - VITE_API_URL=http://localhost:8080
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
